<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SingaravelanNandakumars-MacBook-Pro.local" name="LegacyApp" tests="7" failures="3" timestamp="12 Feb 2018 11:42:14 GMT" time="28.798" errors="0">
  <testcase name="orderItemWithSavedCard" time="3.545" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="5.244" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="4.105" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithAdhocCard" time="2.366" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithAdhocCard(OrdersRegressionCases.java:91)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- orderItemWithAdhocCard -->
  <testcase name="orderItemWithAdhocCard" time="2.32" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <failure type="java.lang.AssertionError" message="expected [3] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [null]
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithAdhocCard(OrdersRegressionCases.java:95)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- orderItemWithAdhocCard -->
  <testcase name="orderItemWithAdhocCard" time="2.167" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <failure type="java.lang.AssertionError" message="expected [There was an error processing this transaction: An error has occurred when making a request (1), and the card has not been charged.] but found [The CVV was not found and is required for this merchant. Please provide one and try again.]">
      <![CDATA[java.lang.AssertionError: expected [There was an error processing this transaction: An error has occurred when making a request (1), and the card has not been charged.] but found [The CVV was not found and is required for this merchant. Please provide one and try again.]
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithAdhocCard(OrdersRegressionCases.java:99)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- orderItemWithAdhocCard -->
  <testcase name="orderWithCloudPass" time="3.009" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
</testsuite> <!-- LegacyApp -->
